[config]
schemaVersion = "0.0.1"

[package]
namespace = "zerp"
name = "DreamDiveTweaks"
versionNumber = "1.9.0"
description = "Hades II mod offering multiple configurable tweaks for Dream Dives. Including but not limited to disabling visage forms, longer runs, some minor fixes and more. Compatible with Zagreus' Journey"
websiteUrl = "https://github.com/adi1998/DreamDiveTweaks"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.110"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"
NikkelM-Resources_In_Chaos_Trials = "1.0.1"
zerp-BoonOverflowFix = "1.0.0"

[package.rom_soft_deps]
NikkelM-Zagreus_Journey = "1.2.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# Uncomment (remove the #) the three lines below if you have any files to copy to the plugins_data folder (like custom .pkg files)
# [[build.copy]]
# source = "./data"
# target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]